# Generated by Django 6.0.1 on 2026-01-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight_lbs', models.IntegerField()),
                ('height_cm', models.IntegerField()),
                ('age', models.IntegerField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('active', 'Active')], max_length=10)),
                ('maintenance_calories', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('cut', 'Cut'), ('maintain', 'Maintain'), ('bulk', 'Bulk')], max_length=10)),
                ('calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
